{
 "title": "ML Serving Monitoring",
 "description": "Мониторинг для сервиса сервинга модели",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Общее по сети", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество запросов за 10 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(http_requests_total{handler!~\"/metrics|/docs|/openapi.json|none\"}[10m])",
     "legendFormat": "{{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "Количество 5** ошибок",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total{status=\"5xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество 4** ошибок",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total{status=\"4xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Логи", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Логи uvicorn",
   "type": "logs",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{logger=\"uvicorn.access\"} |= ``"
    }
   ]
  },
  {
   "title": "Логи приложения",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "{logger=\"src.logger\"} |= ``"
    }
   ]
  },
  { "title": "Общее по ресурсам", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Количество объектов собранных GC в минуту",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "increase(python_gc_objects_collected_total[1m])",
     "legendFormat": "generation {{generation}}"
    }
   ]
  },
  {
   "title": "Виртуальная память в Гб.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"ml-serving\"} / 1073741824",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Количество открытых файловых дескрипторов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 19 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"ml-serving\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Прогноз с передачей координат", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Число запросов с временем выполнения меньше X секунд за сутки",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{handler=\"/api/predict_with_coordinates\"}[24h])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}